# Keybdins para Layout de HY3

binde = $mainMod, Q, hy3:killactive,
bind = $mainMod ,SPACE, togglefloating,
bind = $mainMod, D, exec, $menu
bind = $mainMod, W, hy3:makegroup, tab, ephemeral
bind = $mainMod, E, hy3:changegroup, opposite
bind = $mainMod, S, hy3:makegroup, opposite
bind = $mainMod SHIFT, Q, exec, hyprctl activewindow | grep pid | tr -d 'pid:' | xargs kill -KILL
bind = $mainMod, F, fullscreen
bind = $mainMod, C, exec, $terminal --title=clipse -e 'clipse'

# Scripts
bind = $mainMod SHIFT, O, exec,$pathScripts/blur.sh
bind = $mainMod CONTROL , S, exec,$pathScripts/hyprsunset.sh
bind = $mainMod SHIFT,M, exec, sh $pathScripts/power_menu.sh
bind = $mainMod CONTROL, SPACE, exec, $pathScripts/switch_layout.sh
bind = , PRINT, exec, ~/scripts/screenshot.sh

bind = $mainMod, H, hy3:movefocus, l
bind = $mainMod, L, hy3:movefocus, r
bind = $mainMod, K, hy3:movefocus, u
bind = $mainMod, J, hy3:movefocus, d
bind = $mainMod ALT, H, hy3:focustab, l
bind = $mainMod ALT, L, hy3:focustab, r
bind = $mainMod ALT, K, hy3:focustab, u
bind = $mainMod ALT, J, hy3:focustab, d

bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6
bind = $mainMod, 7, workspace, 7
bind = $mainMod, 8, workspace, 8
bind = $mainMod, 9, workspace, 9
bind = $mainMod, 0, workspace, 10

bind = $mainMod SHIFT, H, hy3:movewindow, l
bind = $mainMod SHIFT, L, hy3:movewindow, r
bind = $mainMod SHIFT, K, hy3:movewindow, u
bind = $mainMod SHIFT, J, hy3:movewindow, d

bind = $mainMod CTRL SHIFT, L, hy3:movetoworkspace, e+1, follow
bind = $mainMod CTRL SHIFT, H, hy3:movetoworkspace, e-1, follow
bindm = $mainMod, mouse:272, movewindow

bind = $mainMod SHIFT, 1, hy3:movetoworkspace, 1 , follow
bind = $mainMod SHIFT, 2, hy3:movetoworkspace, 2 , follow
bind = $mainMod SHIFT, 3, hy3:movetoworkspace, 3 , follow
bind = $mainMod SHIFT, 4, hy3:movetoworkspace, 4 , follow
bind = $mainMod SHIFT, 5, hy3:movetoworkspace, 5 , follow
bind = $mainMod SHIFT, 6, hy3:movetoworkspace, 6 , follow
bind = $mainMod SHIFT, 7, hy3:movetoworkspace, 7 , follow
bind = $mainMod SHIFT, 8, hy3:movetoworkspace, 8 , follow
bind = $mainMod SHIFT, 9, hy3:movetoworkspace, 9 , follow
bind = $mainMod SHIFT, 0, hy3:movetoworkspace, 10 , follow

bind = $mainMod, mouse_down, workspace, e+1
bind = $mainMod, mouse_up, workspace, e-1
bind = $mainMod CONTROL, L, workspace, e+1
bind = $mainMod CONTROL, H, workspace, e-1

bindm = $mainMod, mouse:273, resizewindow

# Cycle windows if floating bring to top
bind = ALT, tab, cyclenext
bind = ALT, tab, bringactivetotop
