source= ~/.config/hypr/monitors.conf                 # Generados por Display Setting que se usa para Hyprland y Sway en este caso para hacer ajustes del monitor
source= ~/.config/hypr/workspaces.conf               # Generados por Display Setting que se usa para Hyprland y Sway en este caso para asignar el workspaces para cada monitor

source= ~/.config/hypr/conf/autostart.conf           # Configuración de Cosas que inician al comienzo de Hyprland
source= ~/.config/hypr/conf/variables.conf           # Variables de Entorno en Hyprland
source = ~/.config/hypr/conf/keybinds_general.conf   # Keybidns Generales en Hyprland
source= ~/.config/hypr/conf/keybinds.conf            # Keybinds Dependiendo del Layout en uso por ejemplo: hy3, dwindle, master o hyprscrolling
source= ~/.config/hypr/conf/animations.conf          # Animaciones en Hyprland
source= ~/.config/hypr/conf/windowrules.conf         # Configuración de las windowrules en Hyprland
source= ~/.config/hypr/conf/workspaces.conf          # Configuración de los workspaces en Hyprland

source = ~/.cache/wal/colors-hyprland.conf           # Colores generados por PYWAL16
permission = /usr/(bin|local/bin)/hyprpm, plugin, allow

xwayland {
  enabled = true
  force_zero_scaling = true
  use_nearest_neighbor = true
}

#####################
### LOOK AND FEEL ###
#####################

# Refer to https://wiki.hyprland.org/Configuring/Variables/

# https://wiki.hyprland.org/Configuring/Variables/#general
general {
    gaps_in = 5
    gaps_out = 15

    border_size = 0
    # https://wiki.hyprland.org/Configuring/Variables/#variable-types for info about colors
    col.active_border = $color5 $color13
    col.inactive_border = $color0

    # Set to true enable resizing windows by clicking and dragging on borders and gaps
    resize_on_border = false

    # Please see https://wiki.hyprland.org/Configuring/Tearing/ before you turn this on
    allow_tearing = false

    layout = dwindle

}

# https://wiki.hyprland.org/Configuring/Variables/#decoration
decoration {
    rounding = 0
    rounding_power = 3

    # Change transparency of focused and unfocused windows
    active_opacity = 1.0
    inactive_opacity = 0.9

    shadow {
        enabled = true
        range = 0
        render_power = 5
        color = $color1
    }

    # https://wiki.hyprland.org/Configuring/Variables/#blur
    blur {
        enabled = true
        size = 5
        passes = 2

        vibrancy = 0.1696
    }
}

dwindle {
    pseudotile = true # Master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
    preserve_split = true

}

# See https://wiki.hyprland.org/Configuring/Master-Layout/ for more
master {
    new_status = master
}

scrolling {
  column_width = 0.8
  fullscreen_on_one_column = true follow_focus = true
  focus_fit_method = 1
}

# https://wiki.hyprland.org/Configuring/Variables/#misc
misc {
  force_default_wallpaper = 1 # Set to 0 or 1 to disable the anime mascot wallpapers
  disable_hyprland_logo = true # If true disables the random hyprland logo / anime girl background. :(
  font_family = Iosevka Nerd Font
  vrr = 3
}

#############
### INPUT ###
#############
# https://wiki.hyprland.org/Configuring/Variables/#input
input {
    kb_layout = latam
    kb_variant = ,qwerty
    kb_model = dell
    kb_options =
    kb_rules =
    numlock_by_default = true
    follow_mouse = 1

    repeat_rate = 40
    repeat_delay = 600
    sensitivity = 0.35 # -1.0 - 1.0, 0 means no modification.

    touchpad {
      natural_scroll = false
      disable_while_typing = false
    }
}
# https://wiki.hyprland.org/Configuring/Variables/#gestures
gestures {
    workspace_swipe_touch = false
}

# Example per-device config
# See https://wiki.hyprland.org/Configuring/Keywords/#per-device-input-configs for more
device {
    name = epic-mouse-v1
    sensitivity = 1.0
}
render {
  cm_fs_passthrough = 0
  cm_auto_hdr = 0
}
