exec-once = systemctl --user import-environment QT_QPA_PLATFORMTHEME
exec-once = sleep 1 && hyprpm reload && pkill waybar
exec-once = sleep 2 && hypridle & swww-daemon & clipse -listen
exec-once = systemctl --user import-environment XDG_SESSION_TYPE XDG_CURRENT_DESKTOP WAYLAND_DISPLAY QT_QPA_PLATFORMTHEME
exec-once = watchexec -r  --watch ~/.config/ags --watch ~/.cache/wal/colors.css -- ags run
# exec-once = ibus start
