source = ~/.cache/wal/colors-hyprland.conf # Colores generados por PYWAL16
plugin {
  hyprscrolling {
    column_width = 0.8
    fullscreen_on_one_column = true follow_focus = true
    focus_fit_method = 1
  }
}
