source = ~/.cache/wal/colors-hyprland.conf # Colores generados por PYWAL16
plugin {
  hyprscrolling {
    column_width = 0.8
    fullscreen_on_one_column = true follow_focus = true
    focus_fit_method = 1
  }
  hyprexpo {
    columns = 3
    gap_size = 7
    bg_col = rgb(111111)
    workspace_method =  first 1 # [center/first] [workspace] e.g. first 1 or center m+1

    gesture_distance = 300 # how far is the "max" for the gesture
  }
    hy3 {
        $bg = $color0
        $fg = $color4
        $trans = rgba(00000000)

        node_collapse_policy = 0
        tab_first_window = false
        # no_gaps_when_only = 1
        group_inset = 5

        tabs {
            border_width = 1
            from_top = false
            padding = 3
            height = 22
            radius = 0

            text_font = Iosevka Slab Term
            text_center = true
            render_text = true
            text_padding = 1
            text_height = 10

            col.active.border = $fg
            col.active.text = $fg
            col.active = $bg

            col.focused.border = $fg
            col.focused.text = $color6
            col.focused = $bg

            col.urgent.border = $fg
            col.urgent.text = $fg
            col.urgent = $bg

            col.inactive.border = $bg
            col.inactive.text = $color9
            col.inactive = $bg

            opacity = 1
            blur = false
        }

    autotile {
      enable = true
      workspaces = 1
    }

    }
}
