# Apps Variables
$terminal = kitty
# GHOSTTY
# $terminal = GTK_IM_MODULE=simple /usr/bin/ghostty --gtk-single-instance=true 

$fileManager = thunar
$menu = rofi -show drun
$browser = zen-browser

$pathScripts = ~/scripts
$mainMod = SUPER
$resetSubMap = hyprctl dispatch submap reset

# See https://wiki.hyprland.org/Configuring/Environment-variables/
env = XCURSOR_THEME,Skyrim
env = XCURSOR_SIZE,28
# env = HYPRCURSOR_SIZE,24
env = TERMINAL,kitty

env = _JAVA_AWT_WM_NONREPARENTING,1
env = XDG_SESSION_TYPE,wayland
env = XDG_SESSION_DESKTOP,Hyprland
env = XDG_CURRENT_DESKTOP,Hyprland

# Wayland backends
env = GDK_BACKEND,wayland
env = CLUTTER_BACKEND,wayland
env = SDL_VIDEODRIVER,wayland

# Firefox
env = MOZ_ENABLE_WAYLAND,1

env = GSK_RENDERER,ngl
# Qt settings
env = QT_AUTO_SCREEN_SCALE_FACTOR,1
env = QT_WAYLAND_DISABLE_WINDOWDECORATION,1
env = QT_QPA_PLATFORMTHEME,qt6ct  # Solo si usas qt6ct
env = QT_QPA_PLATFORM,wayland;xcb

# Escalado (ajusta para HiDPI)
env = QT_SCALE_FACTOR,1
env = GDK_SCALE,1

# ELECTRON
env = ELECTRON_OZONE_PLATFORM_HINT,wayland  # o "wayland" para forzar Wayland
# env = NODE_ENV,wayland  # Algunas apps lo requieren

# IBUS
env = XMODIFIERS,@im=ibus
env = GLFW_IM_MODULE,ibus

# Android Stduio
env = ANDROID_HOME,$HOME/Android/Sdk
env = JAVA_HOME,/usr/lib/jvm/default
env = _JAVA_AWT_WM_NONREPARENTING,1
