# Keybinds para el Layout de Hyprscrolling

binde = $mainMod, Q, killactive
bind = $mainMod SHIFT, Q, exec, hyprctl activewindow | grep pid | tr -d 'pid:' | xargs kill -KILL
bind = $mainMod, D, exec, $menu
bind = $mainMod, F, fullscreen
bind = $mainMod, G, layoutmsg, togglefit
bind = $mainMod SHIFT,M, exec, sh $pathScripts/power_menu.sh

# Keybinds relacionadas con las columnas

# Move focus with SUPER + h j k l keys
bind = $mainMod, H, layoutmsg, focus l
bind = $mainMod, L, layoutmsg, focus r
bind = $mainMod, K, layoutmsg, focus u
bind = $mainMod, J, layoutmsg, focus d

# Switch workspaces with mainMod + [0-9]
bind = $mainMod, 1, workspace, 1 
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6
bind = $mainMod, 7, workspace, 7
bind = $mainMod, 8, workspace, 8
bind = $mainMod, 9, workspace, 9
bind = $mainMod, 0, workspace, 10

# Move active window to a workspace with mainMod + SHIFT + [0-9]
bind = $mainMod SHIFT, 1, layoutmsg, movecoltoworkspace 1
bind = $mainMod SHIFT, 2, layoutmsg, movecoltoworkspace 2
bind = $mainMod SHIFT, 3, layoutmsg, movecoltoworkspace 3
bind = $mainMod SHIFT, 4, layoutmsg, movecoltoworkspace 4
bind = $mainMod SHIFT, 5, layoutmsg, movecoltoworkspace 5
bind = $mainMod SHIFT, 6, layoutmsg, movecoltoworkspace 6
bind = $mainMod SHIFT, 7, layoutmsg, movecoltoworkspace 7
bind = $mainMod SHIFT, 8, layoutmsg, movecoltoworkspace 8
bind = $mainMod SHIFT, 9, layoutmsg, movecoltoworkspace 9
bind = $mainMod SHIFT, 0, layoutmsg, movecoltoworkspace 10

# Mover windows dependiendo de la dirección
bind = $mainMod SHIFT, H, layoutmsg, movewindowto l
bind = $mainMod SHIFT, L, layoutmsg, movewindowto r
bind = $mainMod SHIFT, K, layoutmsg, movewindowto u
bind = $mainMod SHIFT, J, layoutmsg, movewindowto d

# Swap de Columnas
bind = $mainMod CONTROL, H, layoutmsg, swapcol l
bind = $mainMod CONTROL, L, layoutmsg, swapcol r
# Hyprshot

bind = , PRINT, exec, ~/scripts/screenshot.sh
