local g = vim.g
local o = vim.opt

g.mapleader = " "
g.maplocalleader = " "
g.snacks_animate = false

o.swapfile = true
o.smartcase = true
o.laststatus = 3
o.hlsearch = true
o.incsearch = true
o.ignorecase = true
o.relativenumber = true
o.wrap = true
o.clipboard = "unnamedplus"
o.encoding = "utf-8"
o.hidden = true
o.tabstop = 2
o.shiftwidth = 2
o.expandtab = true
o.updatetime = 300
o.termguicolors = true
o.mouse = "a"
o.splitbelow = true
o.splitright = true
o.scrolloff = 9
o.cursorline = true
o.scroll = 6
o.signcolumn = "yes"
o.pumheight = 16
o.winborder = "single"
o.timeout = true
o.timeoutlen = 300
o.undofile = true
