[mgr]
ratio = [2, 3, 4]
sort_by = "natural"
sort_sensitive = true
sort_reverse = false
sort_dir_first = true
linemode = "size"
show_hidden = false
show_symlink = true
scrolloff = 5
[preview]
wrap = "yes"
tab_size = 2
max_width = 5000
max_height = 5000
cache_dir = ""
image_filter = "triangle"
image_quality = 90
sixel_fraction = 15
ueberzug_scale = 1.0
ueberzug_offset = [75, 5, 0, 0]

[input]
cursor_blink = true

[opener]
edit = [
  # editor
  # { run = '$EDITOR  "$@"', orphan = true, desc = "Editor" },
  { run = 'nvim "$@"', block = true, for = "unix", desc = "Neovim" },
  { run = 'zeditor "$@"', block = true, for = "unix", desc = "Zed" },
  { run = 'code"$@"', block = true, for = "unix", desc = "VSCODE" },
]
# edit-album-tracks = [
#   { run = '~/.config/yazi/scripts/edit_album.sh "$1"', block = true, desc = "Editar metadatos", for = "unix" },
# ]
open = [
  # system app
  { run = 'xdg-open "$@"', desc = "Open", for = "linux" },
  { run = 'open "$@"', desc = "Open", for = "macos" },
  { run = 'start "%1"', orphan = true, desc = "Open", for = "windows" },
]
image = [

  { run = 'imv-dir "$@"', orphan = true, desc = "IMV-DIR", for = "linux" },
  { run = 'aseprite "$@"', orphan = true, desc = "Aseprite", for = "linux" },
  { run = 'gimp "$@"', orphan = true, desc = "Gimp", for = "linux" },
  { run = '~/.config/yazi/scripts/wallpaper.sh "$1"', orphan = false, block = false, desc = "Wallpaper", for = "linux" },
]
pdf = [
  { run = "zen-browser %s", orphan = true, desc = "Zen", for = "linux" },
  # { run = "chromium %s", orphan = true, desc = "Chromium", for = "linux" },
  # { run = "zathura-pywal %s", orphan = true, desc = "Zathura", for = "linux" },
  # { run = 'sioyek "$@"', orphan = true, desc = "Sioyek", for = "linux" },
]
epub = [
  { run = "bookokrat %s", block = true, desc = "Bookokrat", for = "linux" },
]
reveal = [
  # reveal
  { run = 'open -R "$1"', desc = "Reveal", for = "macos" },
  { run = 'explorer /select,%1', orphan = true, desc = "Reveal", for = "windows" },
  { run = '''exiftool "$1"; echo "Press enter to exit"; read''', block = true, desc = "Show EXIF", for = "unix" },
]
extract = [
  # extract
  { run = 'unar "$1"', desc = "Extract here", for = "unix" },
  { run = 'unar "%1"', desc = "Extract here", for = "windows" },
  { run = 'ouch d -y %*', desc = "Extract here with ouch", for = "windows" },
  { run = 'ouch d -y "$@"', desc = "Extract here with ouch", for = "unix" },
]
play = [
  # media
  { run = 'mpv "$@"', orphan = true, for = "unix" },
  { run = 'vlc "$@"', orphan = true, desc = "VLC", for = "unix" },
  { run = 'vlc "%1"', orphan = true, desc = "VLC", for = "windows" },
  { run = 'mpv "%1"', block = true, desc = "MPV Player", for = "windows" },
  # { run = '~/.config/yazi/scripts/edit_mp3.sh "$1"', block = true, desc = "Editar metadatos MP3", for = "unix" },
  { run = 'mpv "%1"', orphan = true, for = "windows" },
  { run = '''mediainfo "$1"; echo "Press enter to exit"; read''', block = true, desc = "Show media info", for = "unix" },
]
document = [
  { run = "onlyoffice-desktopeditors %s", orphan = true, desc = "OnlyOffice", for = "linux" },
  # office
  { run = "libreoffice %s", orphan = true, desc = "Libreoffice", for = "linux" },
]
game = [{ run = 'mgba-qt "$@"', orphan = true, desc = "MGBA", for = "unix" }]
nds = [{ run = 'melonDS "$@"', orphan = true, desc = "melonDs", for = "unix" }]

[open]
rules = [
  # rules for open file
  { url = "*/", use = [
    "edit",
    "open",
    "reveal",
  ] },

  { mime = "text/*", use = [
    "edit",
    "reveal",
  ] },
  { mime = "image/*", use = [
    "open",
    "image",
    "reveal",
  ] },
  { mime = "video/*", use = [
    "play",
    "reveal",
  ] },
  { mime = "audio/*", use = [
    "play",
    "reveal",
  ] },
  { mime = "inode/empty", use = [
    "edit",
    "reveal",
  ] },
  { mime = "application/json", use = [
    "edit",
    "reveal",
  ] },
  { mime = "*/javascript", use = [
    "edit",
    "reveal",
  ] },

  { mime = "application/zip", use = [
    "extract",
    "reveal",
  ] },
  { mime = "application/gzip", use = [
    "extract",
    "reveal",
  ] },
  { mime = "application/x-tar", use = [
    "extract",
    "reveal",
  ] },
  { mime = "application/x-bzip", use = [
    "extract",
    "reveal",
  ] },
  { mime = "application/x-bzip2", use = [
    "extract",
    "reveal",
  ] },
  { mime = "application/x-7z-compressed", use = [
    "extract",
    "reveal",
  ] },
  { mime = "application/x-rar", use = [
    "extract",
    "reveal",
  ] },
  { mime = "application/xz", use = [
    "extract",
    "reveal",
  ] },

  { name = "*.{gba,gb,gbc}", use = [
    "game",
  ] },

  { url = "*.pdf", use = [
    "pdf",
  ] },

  { url = "*.epub", use = [
    "epub",
  ] },

  { url = "*.{docx,doc,odt,rtf,pdf,txt,md,tex,wps,wpd,fodt,xlsx,xls,ods,csv,pptx,ppt,odp}", use = [
    "document",
  ] },

  { name = "*.nds", use = [
    "nds",
  ] },
]

[tasks]
micro_workers = 5
macro_workers = 10
bizarre_retry = 5
image_alloc = 536870912
image_bound = [0, 0]
suppress_preload = false

[plugin]
prepend_previewers = [
  # Archive previewer
  { mime = "application/*zip", run = "ouch" },
  { mime = "application/x-tar", run = "ouch" },
  { mime = "application/x-bzip2", run = "ouch" },
  { mime = "application/x-7z-compressed", run = "ouch" },
  { mime = "application/x-rar", run = "ouch" },
  { mime = "application/vnd.rar", run = "ouch" },
  { mime = "application/x-xz", run = "ouch" },
  { mime = "application/xz", run = "ouch" },
  { mime = "application/x-zstd", run = "ouch" },
  { mime = "application/zstd", run = "ouch" },
  { mime = "application/java-archive", run = "ouch" },
]

# [[plugin.prepend_fetchers]]
# id = "git"
# name = "*"
# run = "git"
#
# [[plugin.prepend_fetchers]]
# id = "git"
# name = "*/"
# run = "git"
