local M = {}

M.italic_enabled = false
M.bold_override = { "Comment" }
M.font_custom = {}

local function resolve_style(group_name, has_italic)
	if not has_italic then
		return { italic = nil, bold = nil }
	end

	for _, v in ipairs(M.bold_override) do
		if group_name == v then
			return { italic = false, bold = true }
		end
	end

	return {
		italic = M.italic_enabled,
		bold = false,
	}
end

M.highlights_base = function(colors)
	return {
		Normal = { fg = colors.foreground, bg = "none" },
		NormalNC = { fg = colors.foreground, bg = "none" },
		StatusLineNC = { bg = "none", fg = colors.background },
		StatusLine = { bg = "none", fg = colors.background },
		SignColumn = { bg = "none", fg = colors.background },
		MsgArea = { fg = colors.foreground, bg = colors.background },
		ModeMsg = { fg = colors.foreground, bg = colors.background },
		MsgSeparator = { fg = colors.foreground, bg = colors.background },
		SpellBad = { fg = colors.color2 },
		SpellCap = { fg = colors.color6 },
		SpellLocal = { fg = colors.color4 },
		SpellRare = { fg = colors.color6 },
		Pmenu = { fg = colors.foreground, bg = colors.background },
		PmenuSel = { fg = colors.background, bg = colors.color4 },
		WildMenu = { fg = colors.color7, bg = colors.color4 },
		CursorLineNr = { fg = colors.color7 },
		Comment = { fg = colors.color12, italic = true, bold = false },
		Folded = { fg = colors.color1, bg = colors.background },
		FoldColumn = { fg = colors.color4, bg = colors.background },
		LineNr = { fg = colors.color9, bg = "none" },
		FloatBorder = { fg = colors.foreground, bg = colors.background },
		Whitespace = { fg = colors.color1 },
		VertSplit = { fg = colors.background, bg = colors.color1 },
		CursorLine = { bg = "none" },
		CursorColumn = { bg = "none" },
		ColorColumn = { bg = "none" },
		NormalFloat = { bg = colors.background },
		Visual = { bg = colors.color1, fg = colors.foreground },
		VisualNOS = { bg = colors.background },
		WarningMsg = { fg = colors.color3, bg = colors.background },
		DiffAdd = { fg = colors.background, bg = colors.color4 },
		DiffChange = { fg = colors.background, bg = colors.color5 },
		DiffDelete = { fg = colors.background, bg = colors.color11 },
		QuickFixLine = { bg = colors.color2 },
		PmenuSbar = { bg = colors.background },
		PmenuThumb = { bg = colors.color2 },
		MatchParen = { fg = colors.color4, bg = colors.background },
		Cursor = { fg = colors.foreground, bg = colors.cursor },
		lCursor = { fg = colors.foreground, bg = colors.cursor },
		CursorIM = { fg = colors.foreground, bg = colors.cursor },
		TermCursor = { fg = colors.foreground, bg = colors.cursor },
		TermCursorNC = { fg = colors.foreground, bg = colors.cursor },
		Conceal = { fg = colors.color4, bg = colors.background },
		Directory = { fg = colors.color4 },
		SpecialKey = { fg = colors.color4 },
		Title = { fg = colors.color4 },
		ErrorMsg = { fg = colors.color11, bg = colors.background, bold = true },
		Search = { fg = colors.foreground, bg = colors.color1 },
		IncSearch = { fg = colors.foreground, bg = colors.color1 },
		Substitute = { fg = colors.color1, bg = colors.color6 },
		MoreMsg = { fg = colors.color5 },
		Question = { fg = colors.color5 },
		EndOfBuffer = { fg = colors.background },
		NonText = { fg = colors.color1 },
		Variable = { fg = colors.color14, bold = true },
		String = { fg = colors.color3 },
		Character = { fg = colors.color12 },
		Constant = { fg = colors.color14, italic = false, bold = true },
		Number = { fg = colors.color6 },
		Boolean = { fg = colors.color4, italic = true },
		Float = { fg = colors.color5 },
		Identifier = { fg = colors.color5, italic = false },
		Function = { fg = colors.color8, italic = true, bold = true },
		Operator = { fg = colors.color6 },
		Type = { fg = colors.color12, italic = true },
		StorageClass = { fg = colors.color7 },
		Structure = { fg = colors.color6, italic = true },
		Typedef = { fg = colors.color6, italic = false, bold = true },
		Keyword = { fg = colors.color6 },
		Statement = { fg = colors.color6 },
		Conditional = { fg = colors.color6 },
		Repeat = { fg = colors.color6 },
		Label = { fg = colors.color4 },
		Exception = { fg = colors.color6 },
		Include = { fg = colors.color6, italic = false },
		PreProc = { fg = colors.color6 },
		Define = { fg = colors.color6 },
		Macro = { fg = colors.color6 },
		PreCondit = { fg = colors.color6 },
		Special = { fg = colors.color6, italic = true },
		SpecialChar = { fg = colors.foreground },
		Tag = { fg = colors.color11, bold = true },
		Debug = { fg = colors.color11 },
		Delimiter = { fg = colors.foreground },
		SpecialComment = { fg = colors.color2 },
		Ignore = { fg = colors.color7, bg = colors.background },
		Todo = { fg = colors.color11, bg = colors.background },
		Error = { fg = colors.color11, bg = colors.background },
		TabLine = { fg = colors.color2, bg = colors.background },
		TabLineSel = { fg = colors.foreground, bg = colors.background, bold = true },
		TabLineFill = { fg = colors.foreground, bg = colors.background },
		CmpDocumentationBorder = { fg = colors.foreground, bg = colors.background },
		CmpItemAbbr = { fg = colors.foreground, bg = colors.background },
		CmpItemAbbrDeprecated = { fg = colors.color2, bg = colors.background },
		CmpItemAbbrMatch = { fg = colors.color7, bg = colors.background },
		CmpItemAbbrMatchFuzzy = { fg = colors.color7, bg = colors.background },
		CmpItemKind = { fg = colors.color4, bg = colors.background },
		CmpItemMenu = { fg = colors.color2, bg = colors.background },

		-- treesitter
		TSNote = { fg = colors.background, bg = colors.color5 },
		TSComment = { fg = colors.color1, italic = false },
		TSWarning = { fg = colors.background, bg = colors.color5 },
		TSDanger = { fg = colors.background, bg = colors.color3 },
		TSConstructor = { fg = colors.color6 },
		TSField = { fg = colors.color9 },
		TSInclude = { italic = true },
		TSKeyword = { fg = colors.color6 },
		TSKeywordFunction = { fg = colors.color8, bold = true },
		TSLabel = { fg = colors.color7 },
		TSOperator = { fg = colors.color7 },
		TSParameter = { fg = colors.color5, italic = false, bold = true },
		TSProperty = { fg = colors.color9 },
		TSPunctDelimiter = { fg = colors.color7 },
		TSPunctBracket = { fg = colors.foreground },
		TSPunctSpecial = { fg = colors.color7 },
		TSStringRegex = { fg = colors.color7 },
		TSStringEscape = { fg = colors.color6 },
		TSVariableBuiltin = { fg = colors.color14, italic = true },
		TSTextReference = { fg = colors.color8 },

		-- GitSigns
		GitSignsAdd = { fg = colors.color4 },
		GitSignsChange = { fg = colors.color5 },
		GitSignsDelete = { fg = colors.color11 },

		-- Telescope
		TelescopeBorder = { fg = colors.color1, bg = colors.background },
		TelescopeNormal = { fg = colors.foreground, bg = colors.background },
		TelescopeSelection = { fg = colors.background, bg = colors.color1 },

		-- LSP
		LspInlayHint = { fg = colors.color4 },

		-- Noice
		NoiceCmdline = { fg = colors.color9, italic = false },
		NoiceCmdlinePopup = { fg = colors.color9 },
		NoiceCmdlineIcon = { fg = colors.foreground },
		NoiceCmdlineIconSearch = { fg = colors.color8 },
		NoiceFormatLevelWarn = { fg = colors.color5 },
		NoiceFormatTitle = { fg = colors.color8 },

		-- Flash
		FlashPromptIcon = { fg = colors.foreground },
		FlashPrompt = { fg = colors.color1 },
		FlashLabel = { bg = colors.color4, fg = colors.cursor, bold = true },

		-- WhichKey
		WhichKeyDesc = { fg = colors.color6 },
		WhichKeyTitle = { fg = colors.color7, bold = true, italic = false },
		WhichKeySeparator = { fg = colors.color7 },
		WhichKeyValue = { fg = colors.color5 },
		WhichKeyGroup = { fg = colors.color5 },
		WhichKeyNormal = { fg = colors.color5 },
		WhichKeyBorder = { fg = colors.foreground },
		WhichKeyIcon = { fg = colors.color5 },

		-- Snacks
		SnacksPickerFile = { bg = "none" },
		SnacksPickerDir = { bg = "none" },
		SnacksPickerPathHidden = { bg = "none" },
		SnacksPickerBufnr = { bg = "none" },
		SnacksPickerBufType = { bg = "none" },
		SnacksPickerBox = { bg = "none" },
		SnacksPickerTree = { bg = "none" },
		SnacksPickerInput = { bg = "none" },
		SnacksPickerCode = { bg = "none" },
		SnacksPickerToggle = { bg = "none" },
		SnacksPicker = { bg = "none", nocombine = true },
		SnacksPickerBorder = { bg = "none", nocombine = true },
		SnacksNormal = { bg = "none" },
		SnacksNormalNC = { bg = "none" },
		SnacksBackdrop = { bg = "none" },
		SnacksPickerPickWinCurrent = { bg = "none" },
		SnacksWinBar = { bg = "none" },
		SnacksPickerFooter = { bg = "none" },

		-- Lualine
		LualineNormal = { bg = "none" },
		LualineInactive = { bg = "none" },

		-- Oil
		DiagnosticError = { fg = colors.foreground },
		DiagnosticWarn = { fg = colors.foreground },
		DiagnosticInfo = { fg = colors.foreground },
		DiagnosticHint = { fg = colors.foreground },

		-- RenderMarkdown
		RenderMarkdownH1Bg = { bg = colors.color7, fg = colors.color0, bold = true },
		RenderMarkdownH2Bg = { bg = colors.color6, fg = colors.color0, bold = true },
		RenderMarkdownH3Bg = { bg = colors.color5, fg = colors.color0, bold = true },
		RenderMarkdownH4Bg = { bg = colors.color5, fg = colors.color0, bold = true },
		RenderMarkdownH5Bg = { bg = colors.color4, fg = colors.color0, bold = true },
		RenderMarkdownH6Bg = { bg = colors.color3, fg = colors.color0, bold = true },

		-- Markview
		MarkviewPalette0 = { fg = colors.foreground, bg = colors.background },
		MarkviewPalette0Fg = { fg = colors.foreground },
		MarkviewPalette0Bg = { bg = colors.background },
		MarkviewPalette0Sign = { fg = colors.foreground, bg = colors.background },
		MarkviewPalette1 = { fg = colors.color1, bg = colors.background },
		MarkviewPalette1Fg = { fg = colors.color1 },
		MarkviewPalette1Bg = { bg = colors.color1 },
		MarkviewPalette1Sign = { fg = colors.color1, bg = colors.background },
		MarkviewPalette2 = { fg = colors.color2, bg = colors.background },
		MarkviewPalette2Fg = { fg = colors.color2 },
		MarkviewPalette2Bg = { bg = colors.color2 },
		MarkviewPalette2Sign = { fg = colors.color2, bg = colors.background },
		MarkviewPalette3 = { fg = colors.color3, bg = colors.background },
		MarkviewPalette3Fg = { fg = colors.color3 },
		MarkviewPalette3Bg = { bg = colors.color3 },
		MarkviewPalette3Sign = { fg = colors.color3, bg = colors.background },
		MarkviewPalette4 = { fg = colors.color4, bg = colors.background },
		MarkviewPalette4Fg = { fg = colors.color4 },
		MarkviewPalette4Bg = { bg = colors.color4 },
		MarkviewPalette4Sign = { fg = colors.color4, bg = colors.background },
		MarkviewPalette5 = { fg = colors.color5, bg = colors.background },
		MarkviewPalette5Fg = { fg = colors.color5 },
		MarkviewPalette5Bg = { bg = colors.color5 },
		MarkviewPalette5Sign = { fg = colors.color5, bg = colors.background },
		MarkviewPalette6 = { fg = colors.color6, bg = colors.background },
		MarkviewPalette6Fg = { fg = colors.color6 },
		MarkviewPalette6Bg = { bg = colors.color6 },
		MarkviewPalette6Sign = { fg = colors.color6, bg = colors.background },
		MarkviewHeading1 = { fg = colors.color0, bg = colors.color7, bold = true },
		MarkviewHeading2 = { fg = colors.color0, bg = colors.color6, bold = true },
		MarkviewHeading3 = { fg = colors.color0, bg = colors.color5, bold = true },
		MarkviewHeading4 = { fg = colors.color0, bg = colors.color4, bold = true },
		MarkviewHeading5 = { fg = colors.color0, bg = colors.color3, bold = true },
		MarkviewHeading6 = { fg = colors.color0, bg = colors.color2, bold = true },
		MarkviewHeading1Sign = { fg = colors.color7, bg = colors.background },
		MarkviewHeading2Sign = { fg = colors.color6, bg = colors.background },
		MarkviewHeading3Sign = { fg = colors.color5, bg = colors.background },
		MarkviewHeading4Sign = { fg = colors.color4, bg = colors.background },
		MarkviewHeading5Sign = { fg = colors.color3, bg = colors.background },
		MarkviewHeading6Sign = { fg = colors.color2, bg = colors.background },
		MarkviewCode = { bg = colors.color8, fg = colors.color5 },
		MarkviewCodeInfo = { fg = colors.foreground },
		MarkviewCodeFg = { fg = colors.foreground },
		MarkviewInlineCode = { fg = colors.color6, bg = colors.color8 },
		MarkviewGradient0 = { fg = colors.color0 },
		MarkviewGradient1 = { fg = colors.color1 },
		MarkviewGradient2 = { fg = colors.color2 },
		MarkviewGradient3 = { fg = colors.color3 },
		MarkviewGradient4 = { fg = colors.color4 },
		MarkviewGradient5 = { fg = colors.color5 },
		MarkviewGradient6 = { fg = colors.color6 },
		MarkviewGradient7 = { fg = colors.color7 },
		MarkviewGradient8 = { fg = colors.color8 },
		MarkviewGradient9 = { fg = colors.color9 },
	}
end

return M
